### ISSUE TITLE
Add support for single verified file when testing on multiple targets

### ISSUE THREAD

**Issue by augustoproiete** [VerifyTests/Verify.Terminal#2]
When running Verify tests that target more than one .NET version (e.g. `net7.0;net6.0`), one `.received` file is created for each target:

- `MyApp.TestName.DotNet6_0.received.txt`
- `MyApp.TestName.DotNet7_0.received.txt`

Accepting the changes with `dotnet verify accept` (or interactively via `dotnet verify review`) currently creates two `.verified` files for each corresponding `.received` file. In the example above, it would be:

- `MyApp.TestName.DotNet6_0.verified.txt`
- `MyApp.TestName.DotNet7_0.verified.txt`

However, when the API is identical across targets, a single file `MyApp.TestName.verified.txt` is preferred - and Verify supports that.

It would be great if `Verify.Terminal` could include logic to check if a `MyApp.TestName.verified.txt` (without the Framework name) is present, and allow accepting the changes to that file instead.

**Comment by patriksvensson** [comment]
Yes, absolutely agree with this.

**Comment by patriksvensson** [comment]
@SimonCropp Is the behavior around framework-specific verified.txt files documented somewhere?

**Comment by patriksvensson** [comment]
Will be fixed in the next released version (soon).

<img width="473" alt="image" src="https://user-images.githubusercontent.com/357872/208303683-8ef77b05-c3c8-49f9-8110-cd97956b3a83.png">

**Comment by SimonCropp** [comment]
@patriksvensson https://github.com/VerifyTests/Verify/blob/main/docs/naming.md#received-and-multi-targetting
